### ISSUE TITLE
Need validation for spec fields

### ISSUE THREAD

**Issue by grantseltzer** [grantseltzer/karn#1]
There needs to be a package for validating individual values, as well as a full spec. The package should be consumed internally at all input points, as well as a small CLI tool

**Comment by GrantSeltzer** [comment]
@jfach

**Comment by Jfach** [comment]
I'm on it. 🐎

**Comment by GrantSeltzer** [comment]
Acceptable values for [system call values](http://man7.org/linux/man-pages/man2/syscalls.2.html) and [capabilities](http://wiki.apparmor.net/index.php/AppArmor_Core_Policy_Reference#Capability_rules)

Having helper functions just with maps of those to check would be great so they can be run on values when read in from the declaration files. Probably call [right here](https://github.com/GrantSeltzer/karn/blob/master/generate/create_profiles.go#L83) before the append

**Comment by GrantSeltzer** [comment]
@Jfach If you're interested you can add a cli subcommand for verifying declaration files without generating or anything.
