### ISSUE TITLE
Install make step 

### ISSUE THREAD

**Issue by GrantSeltzer** [GrantSeltzer/karn#16]
This includes creating `~/.karn/declarations` and placing official ones there

**Comment by jrroman** [comment]
@GrantSeltzer would you be able to expand on this a little bit? creating the ~/.karn/declarations and copying the official declarations in is very trival, but i would like to know exactly what you want make install to do aside from add karn to $GOPATH/bin and create the ~/.karn/declarations directory with its official contents. Any clarification would be great, thanks!

**Comment by GrantSeltzer** [comment]
Sure thing. We have a make install target now, but should be expanded to do the following things:

- [x] put the karn binary in the users $GOPATH/bin
- [ ] place the man page (generated by the `man` make target) into `/usr/share/man/man1`
- [ ] create the `~/.karn/declarations` directory

**Comment by jrroman** [comment]
@GrantSeltzer sweet thank you appreciate it.

**Comment by GrantSeltzer** [comment]
No, thank you! :D

**Comment by GrantSeltzer** [comment]
#30
