### ISSUE TITLE
Use gobindata to embed standard declaration bundle into the binary

### ISSUE THREAD

**Issue by GrantSeltzer** [GrantSeltzer/karn#21]
[gobindata](https://github.com/jteeuwen/go-bindata) is a tool for embedding data into a binary. This is perfect for shipping karn as one static binary with all the [entitlement declarations](https://github.com/GrantSeltzer/karn) bundled inside. 

I haven't fully researched go-bindata's interface but this might be best handled by adding a make target to handle it. [Here's](https://github.com/kris-nova/kubicorn/blob/master/Makefile#L23) an example of a project doing it this way.

**Comment by brenol** [comment]
I believe this conflicts with #16 and I actually think this one is more useful. I have done it and will open PR soon

**Comment by GrantSeltzer** [comment]
@brenol Yea I agree with you, I haven't put much thought into how it'd work when someone wants to add custom declarations in addition to custom ones but it's not the most pressing challenge right now. 

Thanks for the interest, looking forward to your PR!

**Comment by GrantSeltzer** [comment]
#27
